[package]
name = "read_tiff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = { default-features = false, version = "0.24.5", features = ["png", "tiff"]}